name: build-test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-mac:
    name: macOS Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: python-version: '3.11'
      - run: pip install --upgrade pip
      - run: pip install torch torchvision onnx onnxruntime rich pytest
      - run: pytest -q

  test-gpu:
    name: GPU Smoke Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: python-version: '3.11'
      - run: |
          pip install --upgrade pip
          pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
          pip install onnx onnxruntime-gpu rich pytest
      - run: pytest -q
      - name: GPU baseline
        run: python3 scripts/baseline_bench.py --iters 1
